config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :categories
    root "dashboards#index"
    resources :products
    devise_for :users
  end
  devise_for :clients
  root "store_front#index"
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :bigint           not null, primary key
#  description :text
#  name        :string
#  quantify    :integer
#  size        :integer
#  status      :boolean          default(TRUE)
#  value       :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :bigint           not null
#  company_id  :bigint           not null
#
# Indexes
#
#  index_products_on_category_id  (category_id)
#  index_products_on_company_id   (company_id)
#
# Foreign Keys
#
#  fk_rails_...  (category_id => categories.id)
#  fk_rails_...  (company_id => companies.id)
#
class Product < ApplicationRecord
  belongs_to :company
  belongs_to :category, optional: true

  has_one_attached :product_image

  validates :name, :quantify, :status, presence: true
  validates :value, presence: true, numericality: { greater_than: 0 }
end

app/controllers/admin/products_controller.rb
module Admin
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy buy_product ]

  # GET /products or /products.json
  def index
    @products = Product.all

    if params[:tab] == "active"
      @products = Product.where(status: true)
    elsif params[:tab] == "inactive"
      @products = Product.where(status: false)
    else
      @products
    end
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_product_path(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to admin_product_path(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to admin_products_path, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(
        :name, :value, :description, :quantify, :company_id, :status,
        :category_id, :product_image
      )
    end
  end  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy buy_product ]

  # GET /products or /products.json
  def index
    @products = Product.all

    if params[:tab] == "active"
      @products = Product.where(status: true)
    elsif params[:tab] == "inactive"
      @products = Product.where(status: false)
    else
      @products
    end
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def buy_product
    @product.sell

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Produto vendido com sucesso." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(
        :name, :value, :description, :quantify, :company_id, :user_id, :client_id,
        :status
      )
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_with(model: [:admin, product], class: "contents") do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :value %>
    <%= form.number_field :value, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :quantify %>
    <%= form.number_field :quantify, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :product_image %>
    <%= form.file_field :product_image %>
  </div>

  <div class="my-5 flex items-center">
    <%= form.check_box :status, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mr-2" %>
    <%= form.label :status %>
  </div>

  <div class="my-5">
    <%= form.label :category_id %>
    <%= form.select :category_id, Category.pluck(:name, :id), class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2" %>
  </div>


  <div class="my-5">
    <%= form.label :company_id %>
    <%= form.select :company_id, Company.pluck(:name, :id), class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/admin/products/_product.html.erb
<div class="px-4 sm:px-6 lg:px-8">
  <div class="sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <h1 class="text-base font-semibold leading-6 text-gray-900">Produtos</h1>
    </div>
    <div class="mt-4 sm:ml-16 sm:mt-0 sm:flex-none">
      <button type="button" class="block rounded-md bg-indigo-600 px-3 py-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Criar produto</button>
    </div>
  </div>
  <div class="mt-8 flow-root">
    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <table class="min-w-full divide-y divide-gray-300">
          <thead>
            <tr>
              <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">Nome</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Valor</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Descrição</th>
              <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Quantidade</th>
              <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-0">
                <span class="sr-only">Edit</span>
              </th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-200">
            <% @products.each do |product| %>
              <tr>
                <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0"><%= product.name %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= product.value %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= product.description %></td>
                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= product.quantify %></td>
                <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-0">
                  <%= link_to "Ver", admin_product_path, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
                  <%= link_to "Editar", edit_admin_product_path(product), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
                </td>
              </tr>
              <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing product</h1>

  <%= render "form", product: @product %>

  <%= link_to "Show this product", admin_product_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to products", admin_products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/admin/products/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="px-4 sm:px-6 lg:px-8">
    <div class="sm:flex sm:items-center">
      <div class="sm:flex-auto">
        <h1 class="text-base font-semibold leading-6 text-gray-900">Produtos</h1>
      </div>
      <div class="mt-4 sm:ml-16 sm:mt-0 sm:flex-none flex items-center gap-4">
        <%= link_to "Criar Produto", new_admin_product_path, class:"block rounded-md bg-indigo-600 px-3 py-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"%>
          <%= link_to "Ativos", admin_products_path(tab: 'active'), class:"text-base font-semibold leading-6 text-gray-900"%>
          <%= link_to "Inativos", admin_products_path(tab: 'inactive'), class:"text-base font-semibold leading-6 text-gray-900"%>
          <%= button_to "Exportar", "#", class:"text-base font-semibold leading-6 text-gray-900"%>
      </div>
    </div>
    <div class="mt-8 flow-root">
      <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
          <table class="min-w-full divide-y divide-gray-300">
            <thead>
              <tr>
                <th scope="col" class="py-3.5 pl-4 pr-3 text-center text-sm font-semibold text-gray-900 sm:pl-0">Nome</th>
                <th scope="col" class="px-3 py-3.5 text-center text-sm font-semibold text-gray-900">Valor</th>
                <th scope="col" class="px-3 py-3.5 text-center text-sm font-semibold text-gray-900">Categoria</th>
                <th scope="col" class="px-3 py-3.5 text-center text-sm font-semibold text-gray-900">Descrição</th>
                <th scope="col" class="px-3 py-3.5 text-center text-sm font-semibold text-gray-900">Quantidade</th>
                <th scope="col" class="px-3 py-3.5 text-center text-sm font-semibold text-gray-900">Status</th>
                <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-0">Ações</th>
              </tr>
            </thead>
            <tbody class="divide-y divide-gray-200">
              <% @products.each do |product| %>
                <tr class="text-center">
                  <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0"><%= product.name %></td>
                  <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= product.value %></td>
                  <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= product.category.name %></td>
                  <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= product.description %></td>
                  <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= product.quantify %></td>
                  <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= product.status ? "Ativo" : "Inativo" %></td>
                  <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-0">
                    <div class="flex justify-center">
                      <%= link_to "Ver", admin_product_path(product), class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
                      <%= link_to "Editar", edit_admin_product_path(product), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
                      <%= button_to "Excluir", admin_product_path(product), method: :delete, data: { confirm: "Tem certeza?"}, class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
                    </div>
                  </td>
                </tr>
                <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Novo produto</h1>

  <%= render "form", product: @product %>

  <%= link_to "Back to products", admin_products_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/admin/products/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

  <div class="relative z-10" role="dialog" aria-modal="true">
    <div class="fixed inset-0 hidden bg-gray-500 bg-opacity-75 transition-opacity md:block"></div>
    <div class="fixed inset-0 z-10 w-screen overflow-y-auto">
      <div class="flex min-h-full items-stretch justify-center text-center md:items-center md:px-2 lg:px-4">
        <div class="flex w-full transform text-left text-base transition md:my-8 md:max-w-2xl md:px-4 lg:max-w-4xl">
          <div class="relative flex w-full items-center overflow-hidden bg-white px-4 pb-8 pt-14 shadow-2xl sm:px-6 sm:pt-8 md:p-6 lg:p-8">
            <%= link_to admin_products_path, class:"absolute right-4 top-4 text-gray-400 hover:text-gray-500 sm:right-6 sm:top-8 md:right-6 md:top-6 lg:right-8 lg:top-8" do %>
              <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
              </svg>
            <% end %>

            <div class="grid w-full grid-cols-1 items-start gap-x-6 gap-y-8 sm:grid-cols-12 lg:gap-x-8">
              <div class="aspect-h-3 aspect-w-2 overflow-hidden rounded-lg bg-gray-100 sm:col-span-4 lg:col-span-5">
                <% if @product.product_image.present? %>
                  <%= image_tag @product.product_image %>
                <% end %>
              </div>
              <div class="sm:col-span-8 lg:col-span-7">
                <h2 class="text-2xl font-bold text-gray-900 sm:pr-12"><%= @product.name %></h2>
                  <p class="text-2xl text-gray-900">R$ <%= @product.value %></p>
                  <p class="text-2xl text-gray-900"><%= @product.description %></p>
                  <p class="text-2xl text-gray-900"><%= @product.status %></p>
                <section aria-labelledby="options-heading" class="mt-10">
                    <%= link_to "Voltar", admin_products_path, class: "mt-6 flex w-full items-center justify-center rounded-md border border-transparent bg-indigo-600 px-8 py-3 text-base font-medium text-white hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"%>
                </section>
            </di>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>